// Copyright Golden Hammer Software
#if defined(GHPUTSTRINGSINTABLES) || defined(GHPUTDECLARATIONS) || !defined(_GH_GAMEIDENTIFIERS_H_)
    #ifndef _GH_GAMEIDENTIFIERS_H_
    #define _GH_GAMEIDENTIFIERS_H_
#endif

#include "GHString/GHEnum.h"

GHIDENTIFIERBEGIN(GHGameIdentifiers)
GHIDENTIFIER(CHALLENGECOMPLETE);
GHIDENTIFIER(GP_NUMUNREADNEWS)

GHIDENTIFIER(M_SAVEOPTIONS)
GHIDENTIFIER(M_RESETOPTIONS)

GHIDENTIFIER(M_SETHANDGESTURE)
GHIDENTIFIER(M_RESETCURRENTHANDGESTURE)

GHIDENTIFIER(M_REQUESTRATING)

GHIDENTIFIEREND

#include "GHString/GHEnumEnd.h"

#endif
