// Copyright Golden Hammer Software
#if defined(GHPUTSTRINGSINTABLES) || defined(GHPUTDECLARATIONS) || !defined(_GHMULTIPLAYERMATCHOUTCOME_H_)
#ifndef _GHMULTIPLAYERMATCHOUTCOME_H_
#define _GHMULTIPLAYERMATCHOUTCOME_H_
#endif

#include "GHString/GHEnum.h"

GHENUMBEGIN(GHMultiplayerMatchOutcome)
GHENUM(GHMULTIPLAYERMATCH_WON)
GHENUM(GHMULTIPLAYERMATCH_LOST)
GHENUM(GHMULTIPLAYERMATCH_TIED)
GHENUMEND

#include "GHString/GHEnumEnd.h"

#endif
