// Copyright Golden Hammer Software
#if defined(GHPUTSTRINGSINTABLES) || defined(GHPUTDECLARATIONS) || !defined(_GH_STATTRACKERIDENTIFIERS_H_)
#ifndef _GH_STATTRACKERIDENTIFIERS_H_
#define _GH_STATTRACKERIDENTIFIERS_H_
#endif

#include "GHString/GHEnum.h"

GHIDENTIFIERBEGIN(GHStatTrackerIdentifiers)
GHIDENTIFIER(MSG_SHOWLEADERBOARD)
GHIDENTIFIER(MSG_SHOWACHIEVEMENTS)
GHIDENTIFIER(GP_SUPPORTSACHIEVEMENTS)
GHIDENTIFIER(GP_SUPPORTSLEADERBOARDS)
GHIDENTIFIEREND

#include "GHString/GHEnumEnd.h"

#endif
