// Copyright 2010 Golden Hammer Software
#if defined(GHPUTSTRINGSINTABLES) || defined(GHPUTDECLARATIONS) || !defined(_GHWPIDENTIFIERS_H_)
#ifndef _GHWPIDENTIFIERS_H_
#define _GHWPIDENTIFIERS_H_
#endif

#include "GHEnum.h"

GHIDENTIFIERBEGIN(GHWPIdentifiers)
GHIDENTIFIER(WP_IAPCALLBACK)
GHIDENTIFIER(WP_IAPNAME)
GHIDENTIFIER(WP_IAPRESULT)
GHIDENTIFIEREND

#include "GHEnumEnd.h"

#endif
