// Copyright 2010 Golden Hammer Software
#if defined(GHPUTSTRINGSINTABLES) || defined(GHPUTDECLARATIONS) || !defined(_GHAPPLEIDENTIFIERS_H_)
#ifndef _GHAPPLEIDENTIFIERS_H_
#define _GHAPPLEIDENTIFIERS_H_
#endif

#include "GHString/GHEnum.h"

GHIDENTIFIERBEGIN(GHAppleIdentifiers)
GHIDENTIFIER(MULTIPLAYERNAMES)
GHIDENTIFIER(MULTIPLAYERMATCHREQUESTED)
GHIDENTIFIER(NEXTMULTIPLAYERMATCHREQUESTED)
GHIDENTIFIER(MULTIPLAYERMATCHRETURNED)
GHIDENTIFIER(MULTIPLAYERMATCHCANCELLED)
GHIDENTIFIER(MULTIPLAYERMATCHDIALOGDISPLAYED)
GHIDENTIFIER(MULTIPLAYERTURNTAKEN)
GHIDENTIFIER(MULTIPLAYERACTIVEMATCHNUMBERCHANGED)
GHIDENTIFIER(MULTIPLAYERCLEARMATCH)
GHIDENTIFIER(MULTIPLAYERMATCHDATA)
GHIDENTIFIER(MULTIPLAYERMATCHDATALENGTH)
GHIDENTIFIER(MULTIPLAYERMATCHISOURTURN)
GHIDENTIFIER(MULTIPLAYERMATCHGAMEISOVER)
GHIDENTIFIER(MULTIPLAYERMATCHRESULTS)
GHIDENTIFIER(MULTIPLAYERMATCHCOUNT)
GHIDENTIFIER(IAPINFORMGAME)
GHIDENTIFIER(IAPITEMID)
GHIDENTIFIER(IAPSUCCESS)
GHIDENTIFIER(IAPRESTORE)
GHIDENTIFIER(GP_GC_AUTHVIEWWAITING)
GHIDENTIFIER(M_GC_SHOWAUTHVIEW)
GHIDENTIFIEREND

#include "GHString/GHEnumEnd.h"

#endif
