// Copyright Golden Hammer Software
#if defined(GHPUTSTRINGSINTABLES) || defined(GHPUTDECLARATIONS) || !defined(_GHGUIPROPERTIES_H_)
#ifndef _GHGUIPROPERTIES_H_
#define _GHGUIPROPERTIES_H_
#endif

#include "GHString/GHEnum.h"

GHIDENTIFIERBEGIN(GHGUIProperties)
GHIDENTIFIER(GP_PARENTWIDGET)
GHIDENTIFIER(GP_PARENTWIDGETRES)
GHIDENTIFIER(GP_WIDGETRESOURCEPTR)
GHIDENTIFIER(GP_WIDGETFILENAME) //the widget ID. by default it is the filename
GHIDENTIFIER(GP_ADDTOSTACK)
GHIDENTIFIER(GP_WIDESCREEN)
GHIDENTIFIER(GP_PRIORITY)
GHIDENTIFIER(GP_GUICATEGORY) // for pushing different activatable layers to the gui mgr.
GHIDENTIFIER(GP_TRANSITIONDESC)
GHIDENTIFIER(GUIPUSH)
GHIDENTIFIER(GUIPOP)
GHIDENTIFIER(GUIBACK)
GHIDENTIFIER(GP_GUISCROLL) // GHGUIScroll*
GHIDENTIFIER(GP_GUICANVAS)
GHIDENTIFIER(M_TOGGLEGUIDRAW)
GHIDENTIFIEREND

#include "GHString/GHEnumEnd.h"

#endif

