// Copyright 2010 Golden Hammer Software
#if defined(GHPUTSTRINGSINTABLES) || defined(GHPUTDECLARATIONS) || !defined(_GHRAGDOLLTOOLPROPERTIES_H_)
#ifndef _GHRAGDOLLTOOLPROPERTIES_H_
#define _GHRAGDOLLTOOLPROPERTIES_H_
#endif

#include "GHEnum.h"

GHIDENTIFIERBEGIN(GHRagdollToolProperties)
GHIDENTIFIER(SELECTEDBONE)
GHIDENTIFIER(COMMANDTEXT)
GHIDENTIFIER(COMMANDRESULT)

GHIDENTIFIER(MAININPUTSTATE)
GHIDENTIFIER(COMMANDINPUTSTATE)
GHIDENTIFIEREND

#include "GHEnumEnd.h"

#endif

