// Copyright 2010 Golden Hammer Software
#if defined(GHPUTSTRINGSINTABLES) || defined(GHPUTDECLARATIONS) || !defined(_GT_IDENTIFIERS_H_)
#ifndef _GT_IDENTIFIERS_H_
#define _GT_IDENTIFIERS_H_
#endif

#include "GHString/GHEnum.h"

GHIDENTIFIERBEGIN(GTIdentifiers)

GHIDENTIFIER(S_MAIN)
GHIDENTIFIER(S_CONSOLE)

GHIDENTIFIER(M_CREATEPANEL)
GHIDENTIFIER(M_DELETEPANEL)
GHIDENTIFIER(M_SELECTPANEL)
GHIDENTIFIER(M_MOVEEND)
GHIDENTIFIER(M_MOVEPANEL)
GHIDENTIFIER(M_UNDO)
GHIDENTIFIER(M_REDO)
GHIDENTIFIER(M_CHANGE)
GHIDENTIFIER(M_SETCOLOR)
GHIDENTIFIER(M_SETTEXTURE)
GHIDENTIFIER(M_SAVE)
GHIDENTIFIER(M_LOAD)
GHIDENTIFIER(M_CLEARALLDATA)
GHIDENTIFIER(M_SHIFTPRESSED)
GHIDENTIFIER(M_SHIFTRELEASED)
GHIDENTIFIER(M_SETMOVETYPE)
GHIDENTIFIER(M_UPDATETEXT)

GHIDENTIFIER(MP_SELECTPOINT)
GHIDENTIFIER(MP_MOVEDELTA)
GHIDENTIFIER(MP_CHANGE)
GHIDENTIFIER(MP_CREATEASCHILD)
GHIDENTIFIER(MP_COLOR)
GHIDENTIFIER(MP_OLDID)
GHIDENTIFIER(MP_NEWID)

GHIDENTIFIER(GP_CONSOLEINPUTSTR)
GHIDENTIFIER(GP_CONSOLERESULTSTR)
GHIDENTIFIER(GP_CURRSELECTEDNAME)
GHIDENTIFIER(GP_CURRSELECTEDDESC)

GHIDENTIFIEREND

#endif