// Copyright 2010 Golden Hammer Software
#if defined(GHPUTSTRINGSINTABLES) || defined(GHPUTDECLARATIONS) || !defined(_GHIOSIDENTIFIERS_H_)
#ifndef _GHIOSIDENTIFIERS_H_
#define _GHIOSIDENTIFIERS_H_
#endif

#include "GHString/GHEnum.h"

GHIDENTIFIERBEGIN(GHiOSIdentifiers)
GHIDENTIFIER(UISHOWKEYBOARD)
GHIDENTIFIER(UIHIDEKEYBOARD)
GHIDENTIFIER(APPDIDENTERFOREGROUND)
GHIDENTIFIEREND

#include "GHString/GHEnumEnd.h"

#endif
