#if defined(GHPUTSTRINGSINTABLES) || defined(GHPUTDECLARATIONS) || !defined(_GHHMDIDENTIFIERS_H_)
#ifndef _GHHMDIDENTIFIERS_H_
#define _GHHMDIDENTIFIERS_H_
#endif

#include "GHString/GHEnum.h"

GHIDENTIFIERBEGIN(GHHMDIdentifiers)
GHIDENTIFIER(M_HMDCENTEROFFSETACCEPT)
GHIDENTIFIER(M_HMDCENTEROFFSETCANCEL)
GHIDENTIFIER(M_HMDCENTEROFFSETRESETTODEFAULT)
GHIDENTIFIER(M_SETAVATARCAPABILITY)
GHIDENTIFIER(MP_CONTROLLERS)
GHIDENTIFIEREND

#include "GHString/GHEnumEnd.h"

#endif
