// Copyright Golden Hammer Software
#if defined(GHPUTSTRINGSINTABLES) || defined(GHPUTDECLARATIONS) || !defined(_GHRENDERPROPS_H_)
#ifndef _GHRENDERPROPS_H_
#define _GHRENDERPROPS_H_
#endif

#include "GHString/GHEnum.h"

GHIDENTIFIERBEGIN(GHRenderProperties)
GHIDENTIFIER(GRAPHICSQUALITY)
GHIDENTIFIER(M_GRAPHICSQUALITYCHANGED)
GHIDENTIFIER(DONTUSEMIPMAPS)
GHIDENTIFIER(DEVICELOST) //message
GHIDENTIFIER(DEVICEREINIT) // message
GHIDENTIFIER(GP_NUMDRAWS)
GHIDENTIFIER(GP_NUMVERTS)
GHIDENTIFIER(GP_NUMMATS)
GHIDENTIFIER(GP_GHMDESC)
GHIDENTIFIER(GP_KEEPTEXTUREDATA) // 0 if throw away on load.
GHIDENTIFIER(M_HMDACTIVATED) // headset is worn
GHIDENTIFIER(M_HMDDEACTIVATED) // headset was removed.
GHIDENTIFIER(GP_HMDACTIVATED) // 0 if headset is not worn.
GHIDENTIFIER(GP_TEXTUREFORMAT) // texture format for loading from memory.
GHIDENTIFIER(GP_WIDTH)
GHIDENTIFIER(GP_HEIGHT)
GHIDENTIFIER(GP_NUMMIPS)
GHIDENTIFIER(GP_NOHEADER)
GHIDENTIFIER(GP_LOADINGMATERIALOVERRIDE) // flag to lower some warning messages while loading a material override mat.
GHIDENTIFIER(M_SCREENSHOT)
GHIDENTIFIEREND

#include "GHString/GHEnumEnd.h"

#endif
