// Copyright Golden Hammer Software
#if defined(GHPUTSTRINGSINTABLES) || !defined(_GHTextureFormat_H_)
#ifndef _GHTextureFormat_H_
#define _GHTextureFormat_H_
#endif

#include "GHString/GHEnum.h"

// A list of texture formats for loading
// Platform independent names for d3d/gl formats.
// This is not expected to be a complete list and should be appended or revised as necessary.
// todo: any additional formats as needed
GHENUMBEGIN(GHTextureFormat)

GHENUM(TF_UNKNOWN) // unspecified format.

GHENUM(TF_RGB8) // uncompressed 24 bit texture
GHENUM(TF_RGBA8) // uncompressed 32 bit texture
GHENUM(TF_BGR8)
GHENUM(TF_BGRA8)
GHENUM(TF_GRGB8888)

GHENUM(TF_DEPTH)

// PUT ALL UNCOMPRESSED TYPES BEFORE THIS LINE.
GHENUM(TF_MAX_UNCOMPRESSED) 

GHENUM(TF_PVRTC_2BPP_RGB)
GHENUM(TF_PVRTC_2BPP_RGBA)
GHENUM(TF_PVRTC_4BPP_RGB)
GHENUM(TF_PVRTC_4BPP_RGBA)
GHENUM(TF_PVRTC2_2BPP)
GHENUM(TF_PVRTC2_4BPP)

GHENUM(TF_ETC1)
GHENUM(TF_ETC2_RGB)
GHENUM(TF_ETC2_RGBA)
GHENUM(TF_ETC2_RGB_A1)

GHENUM(TF_DXT1) // aka BC1
GHENUM(TF_DXT2)
GHENUM(TF_DXT3) // aka BC2
GHENUM(TF_DXT4)
GHENUM(TF_DXT5) // aka BC3
GHENUM(TF_BC4)
GHENUM(TF_BC5)
GHENUM(TF_BC6)
GHENUM(TF_BC7)

GHENUM(TF_UYVY)
GHENUM(TF_YUY2)
GHENUM(TF_BW1BPP)
GHENUM(TF_R9G9B9E5_SHARED_EXPONENT)

GHENUM(TF_EAC_R11)
GHENUM(TF_EAC_RG11)

GHENUM(TF_ASTC_4x4)
GHENUM(TF_ASTC_5x4)
GHENUM(TF_ASTC_5x5)
GHENUM(TF_ASTC_6x5)
GHENUM(TF_ASTC_6x6)
GHENUM(TF_ASTC_8x5)
GHENUM(TF_ASTC_8x6)
GHENUM(TF_ASTC_8x8)
GHENUM(TF_ASTC_10x5)
GHENUM(TF_ASTC_10x6)
GHENUM(TF_ASTC_10x8)
GHENUM(TF_ASTC_10x10)
GHENUM(TF_ASTC_12x10)
GHENUM(TF_ASTC_12x12)
GHENUM(TF_ASTC_3x3x3)
GHENUM(TF_ASTC_4x3x3)
GHENUM(TF_ASTC_4x4x3)
GHENUM(TF_ASTC_4x4x4)
GHENUM(TF_ASTC_5x4x4)
GHENUM(TF_ASTC_5x5x4)
GHENUM(TF_ASTC_5x5x5)
GHENUM(TF_ASTC_6x5x5)
GHENUM(TF_ASTC_6x6x5)
GHENUM(TF_ASTC_6x6x6)

GHENUM(TF_ETC1_RGB8_OES)
GHENUM(TF_COMPRESSED_RGB8_ETC2)
GHENUM(TF_COMPRESSED_SRGB8_ETC2)
GHENUM(TF_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2)
GHENUM(TF_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2)
GHENUM(TF_COMPRESSED_RGBA8_ETC2_EAC)
GHENUM(TF_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC)
GHENUM(TF_COMPRESSED_R11_EAC)
GHENUM(TF_COMPRESSED_SIGNED_R11_EAC)
GHENUM(TF_COMPRESSED_RG11_EAC)
GHENUM(TF_COMPRESSED_SIGNED_RG11_EAC)

GHENUMEND

#include "GHString/GHEnumEnd.h"

#endif
