// Copyright Golden Hammer Software
#if defined(GHPUTSTRINGSINTABLES) || defined(GHPUTDECLARATIONS) || !defined(_GHPHYSICSSHAPETYPE_H_)
#ifndef _GHPHYSICSSHAPETYPE_H_
#define _GHPHYSICSSHAPETYPE_H_
#endif

#include "GHString/GHEnum.h"

GHENUMBEGIN(GHPhysicsShapeType)
GHENUM(PS_BOX)
GHENUM(PS_SPHERE)
GHENUM(PS_CYLINDER)
GHENUM(PS_CAPSULE)
GHENUM(PS_PLANE)
GHENUM(PS_MESH)
GHENUM(PS_STATICMESH)
GHENUM(PS_CONVEXHULL)
GHENUM(PS_HEIGHTFIELD)
GHENUMEND

#include "GHString/GHEnumEnd.h"

#endif

