// Copyright 2010 Golden Hammer Software
#if defined(GHPUTSTRINGSINTABLES) || defined(GHPUTDECLARATIONS) || !defined(_GHANDROIDIDENTIFIERS_H_)
#ifndef _GHANDROIDIDENTIFIERS_H_
#define _GHANDROIDIDENTIFIERS_H_
#endif

#include "GHString/GHEnum.h"

GHIDENTIFIERBEGIN(GHAndroidIdentifiers)
GHIDENTIFIER(IAPINFORMGAME)
GHIDENTIFIER(IAPITEMID)
GHIDENTIFIER(IAPSUCCESS)
GHIDENTIFIEREND

#include "GHString/GHEnumEnd.h"

#endif
