// Copyright Golden Hammer Software
#if defined(GHPUTSTRINGSINTABLES) || !defined(_GHKEYDEF_H_)
#ifndef _GHKEYDEF_H_
    #define _GHKEYDEF_H_
#endif

#include "GHString/GHEnum.h"

GHENUMBEGIN(GHKeyDef)
GHENUMVAL(KEY_UPARROW, 0)
GHENUMVAL(KEY_DOWNARROW, 1)
GHENUMVAL(KEY_LEFTARROW, 2)
GHENUMVAL(KEY_RIGHTARROW, 3)
GHENUMVAL(KEY_ENTER, 13)
GHENUMVAL(KEY_SHIFT, 16)
GHENUMVAL(KEY_CONTROL, 17)
GHENUMVAL(KEY_ESC, 27)
GHENUMVAL(KEY_BACKSPACE, 127)
GHENUMVAL(KEY_DELETE, 40)
GHENUMVAL(KEY_INS, 399)
GHENUMVAL(KEY_MOUSE1, 401)
GHENUMVAL(KEY_MOUSE2, 402)
GHENUMVAL(KEY_MOUSE3, 403)
// the vals 3*maxPointers are reserved for additional mouse1/2/3s
GHENUMVAL(KEY_MOUSEWHEEL, 600) // contains the amount the (singular) mouse wheel moved.

// xbox controller mapping.
GHENUMVAL(KEY_GP_A, 0)
GHENUMVAL(KEY_GP_B, 3)
GHENUMVAL(KEY_GP_X, 1)
GHENUMVAL(KEY_GP_Y, 2)
GHENUMVAL(KEY_GP_LEFTBUMPER, 4)
GHENUMVAL(KEY_GP_LEFTTRIGGER, 5)
GHENUMVAL(KEY_GP_RIGHTBUMPER, 6)
GHENUMVAL(KEY_GP_RIGHTTRIGGER, 7)
GHENUMVAL(KEY_GP_LEFTSTICKBUTTON, 8)
GHENUMVAL(KEY_GP_RIGHTSTICKBUTTON, 9)
GHENUMVAL(KEY_GP_START, 10)
GHENUMVAL(KEY_GP_BACK, 11)
GHENUMVAL(KEY_GP_DPADUP, 12)
GHENUMVAL(KEY_GP_DPADDOWN, 13)
GHENUMVAL(KEY_GP_DPADLEFT, 14)
GHENUMVAL(KEY_GP_DPADRIGHT, 15)
GHENUMVAL(KEY_GP_LEFTMENU, 16) // often shared with back
GHENUMVAL(KEY_GP_RIGHTMENU, 17) // often shared with start

//for capacative button touch detection
GHENUMVAL(BEGIN_TOUCH_VALS, 50)
GHENUMVAL(TOUCH_GP_A, 50)
GHENUMVAL(TOUCH_GP_B, 53)
GHENUMVAL(TOUCH_GP_X, 51)
GHENUMVAL(TOUCH_GP_Y, 52)
GHENUMVAL(TOUCH_GP_LEFTBUMPER, 54)
GHENUMVAL(TOUCH_GP_LEFTTRIGGER, 55)
GHENUMVAL(TOUCH_GP_RIGHTBUMPER, 56)
GHENUMVAL(TOUCH_GP_RIGHTTRIGGER, 57)
GHENUMVAL(TOUCH_GP_LEFTSTICKBUTTON, 58)
GHENUMVAL(TOUCH_GP_RIGHTSTICKBUTTON, 59)
GHENUMVAL(TOUCH_GP_START, 60)
GHENUMVAL(TOUCH_GP_BACK, 61)
GHENUMVAL(TOUCH_GP_DPADUP, 62)
GHENUMVAL(TOUCH_GP_DPADDOWN, 63)
GHENUMVAL(TOUCH_GP_DPADLEFT, 64)
GHENUMVAL(TOUCH_GP_DPADRIGHT, 65)
GHENUMVAL(TOUCH_GP_LEFTTHUMBREST, 70)
GHENUMVAL(TOUCH_GP_RIGHTTHUMBREST, 71)

//poses
GHENUMVAL(POSE_GP_LEFTINDEXPOINT, 72)
GHENUMVAL(POSE_GP_RIGHTINDEXPOINT, 73)
GHENUMVAL(POSE_GP_LEFTTHUMBUP, 74)
GHENUMVAL(POSE_GP_RIGHTTHUMBUP, 75)
GHENUMVAL(END_TOUCH_VALS, 76)

GHENUM(KEY_ANY)
GHENUMEND

#include "GHString/GHEnumEnd.h"

#endif

