// Copyright 2010 Golden Hammer Software
#if defined(GHPUTSTRINGSINTABLES) || defined(GHPUTDECLARATIONS) || !defined(_GHBBIDENTIFIERS_H_)
#ifndef _GHBBIDENTIFIERS_H_
#define _GHBBIDENTIFIERS_H_
#endif

#include "GHEnum.h"

GHIDENTIFIERBEGIN(GHBBIdentifiers)
GHIDENTIFIER(SCORELOOPDISPLAYGLOBAL)
GHIDENTIFIER(SCORELOOPDISPLAYFRIENDS)
GHIDENTIFIER(SCORELOOPDISPLAYACHIEVEMENTS)
GHIDENTIFIER(SCORELOOP_DISPLAY_IS_GLOBAL)
GHIDENTIFIER(SCORELOOP_WAITING)
GHIDENTIFIEREND

#include "GHEnumEnd.h"

#endif
